packages:
  - '.'
  - 'extensions/*'
  - 'server'
  - 'packages/*'

allowBuilds:
  '@google/genai': true
  '@turbodocx/html-to-docx': true
  better-sqlite3: false
  core-js: true
  esbuild: true
  lightningcss: true
  protobufjs: true
  sharp: true
  workerd: true

trustLockfile: true
