/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BookmarksRouteImport } from './routes/bookmarks'
import { Route as CreatorRouteImport } from './routes/creator'
import { Route as EcommerceRouteImport } from './routes/ecommerce'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as ObsidianRouteImport } from './routes/obsidian'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as WorkbenchRouteImport } from './routes/workbench'
import { Route as CreatorIndexRouteImport } from './routes/creator/index'
import { Route as CreatorArchiveRouteImport } from './routes/creator/archive'
import { Route as CreatorMaterialsRouteImport } from './routes/creator/materials'
import { Route as CreatorRadarRouteImport } from './routes/creator/radar'
import { Route as CreatorStudioRouteImport } from './routes/creator/studio'
import { Route as CreatorToolsRouteImport } from './routes/creator/tools'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorRoute = CreatorRouteImport.update({
  id: '/creator',
  path: '/creator',
  getParentRoute: () => rootRouteImport,
} as any)
const EcommerceRoute = EcommerceRouteImport.update({
  id: '/ecommerce',
  path: '/ecommerce',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const ObsidianRoute = ObsidianRouteImport.update({
  id: '/obsidian',
  path: '/obsidian',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkbenchRoute = WorkbenchRouteImport.update({
  id: '/workbench',
  path: '/workbench',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorIndexRoute = CreatorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CreatorRoute,
} as any)
const CreatorArchiveRoute = CreatorArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => CreatorRoute,
} as any)
const CreatorMaterialsRoute = CreatorMaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => CreatorRoute,
} as any)
const CreatorRadarRoute = CreatorRadarRouteImport.update({
  id: '/radar',
  path: '/radar',
  getParentRoute: () => CreatorRoute,
} as any)
const CreatorStudioRoute = CreatorStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => CreatorRoute,
} as any)
const CreatorToolsRoute = CreatorToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => CreatorRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bookmarks': typeof BookmarksRoute
  '/creator': typeof CreatorRouteWithChildren
  '/ecommerce': typeof EcommerceRoute
  '/editor': typeof EditorRoute
  '/learn': typeof LearnRoute
  '/obsidian': typeof ObsidianRoute
  '/skills': typeof SkillsRoute
  '/workbench': typeof WorkbenchRoute
  '/creator/archive': typeof CreatorArchiveRoute
  '/creator/materials': typeof CreatorMaterialsRoute
  '/creator/radar': typeof CreatorRadarRoute
  '/creator/studio': typeof CreatorStudioRoute
  '/creator/tools': typeof CreatorToolsRoute
  '/creator/': typeof CreatorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bookmarks': typeof BookmarksRoute
  '/ecommerce': typeof EcommerceRoute
  '/editor': typeof EditorRoute
  '/learn': typeof LearnRoute
  '/obsidian': typeof ObsidianRoute
  '/skills': typeof SkillsRoute
  '/workbench': typeof WorkbenchRoute
  '/creator/archive': typeof CreatorArchiveRoute
  '/creator/materials': typeof CreatorMaterialsRoute
  '/creator/radar': typeof CreatorRadarRoute
  '/creator/studio': typeof CreatorStudioRoute
  '/creator/tools': typeof CreatorToolsRoute
  '/creator': typeof CreatorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bookmarks': typeof BookmarksRoute
  '/creator': typeof CreatorRouteWithChildren
  '/ecommerce': typeof EcommerceRoute
  '/editor': typeof EditorRoute
  '/learn': typeof LearnRoute
  '/obsidian': typeof ObsidianRoute
  '/skills': typeof SkillsRoute
  '/workbench': typeof WorkbenchRoute
  '/creator/archive': typeof CreatorArchiveRoute
  '/creator/materials': typeof CreatorMaterialsRoute
  '/creator/radar': typeof CreatorRadarRoute
  '/creator/studio': typeof CreatorStudioRoute
  '/creator/tools': typeof CreatorToolsRoute
  '/creator/': typeof CreatorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/bookmarks'
    | '/creator'
    | '/ecommerce'
    | '/editor'
    | '/learn'
    | '/obsidian'
    | '/skills'
    | '/workbench'
    | '/creator/archive'
    | '/creator/materials'
    | '/creator/radar'
    | '/creator/studio'
    | '/creator/tools'
    | '/creator/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/bookmarks'
    | '/ecommerce'
    | '/editor'
    | '/learn'
    | '/obsidian'
    | '/skills'
    | '/workbench'
    | '/creator/archive'
    | '/creator/materials'
    | '/creator/radar'
    | '/creator/studio'
    | '/creator/tools'
    | '/creator'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/bookmarks'
    | '/creator'
    | '/ecommerce'
    | '/editor'
    | '/learn'
    | '/obsidian'
    | '/skills'
    | '/workbench'
    | '/creator/archive'
    | '/creator/materials'
    | '/creator/radar'
    | '/creator/studio'
    | '/creator/tools'
    | '/creator/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BookmarksRoute: typeof BookmarksRoute
  CreatorRoute: typeof CreatorRouteWithChildren
  EcommerceRoute: typeof EcommerceRoute
  EditorRoute: typeof EditorRoute
  LearnRoute: typeof LearnRoute
  ObsidianRoute: typeof ObsidianRoute
  SkillsRoute: typeof SkillsRoute
  WorkbenchRoute: typeof WorkbenchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator': {
      id: '/creator'
      path: '/creator'
      fullPath: '/creator'
      preLoaderRoute: typeof CreatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecommerce': {
      id: '/ecommerce'
      path: '/ecommerce'
      fullPath: '/ecommerce'
      preLoaderRoute: typeof EcommerceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obsidian': {
      id: '/obsidian'
      path: '/obsidian'
      fullPath: '/obsidian'
      preLoaderRoute: typeof ObsidianRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workbench': {
      id: '/workbench'
      path: '/workbench'
      fullPath: '/workbench'
      preLoaderRoute: typeof WorkbenchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/': {
      id: '/creator/'
      path: '/'
      fullPath: '/creator/'
      preLoaderRoute: typeof CreatorIndexRouteImport
      parentRoute: typeof CreatorRoute
    }
    '/creator/archive': {
      id: '/creator/archive'
      path: '/archive'
      fullPath: '/creator/archive'
      preLoaderRoute: typeof CreatorArchiveRouteImport
      parentRoute: typeof CreatorRoute
    }
    '/creator/materials': {
      id: '/creator/materials'
      path: '/materials'
      fullPath: '/creator/materials'
      preLoaderRoute: typeof CreatorMaterialsRouteImport
      parentRoute: typeof CreatorRoute
    }
    '/creator/radar': {
      id: '/creator/radar'
      path: '/radar'
      fullPath: '/creator/radar'
      preLoaderRoute: typeof CreatorRadarRouteImport
      parentRoute: typeof CreatorRoute
    }
    '/creator/studio': {
      id: '/creator/studio'
      path: '/studio'
      fullPath: '/creator/studio'
      preLoaderRoute: typeof CreatorStudioRouteImport
      parentRoute: typeof CreatorRoute
    }
    '/creator/tools': {
      id: '/creator/tools'
      path: '/tools'
      fullPath: '/creator/tools'
      preLoaderRoute: typeof CreatorToolsRouteImport
      parentRoute: typeof CreatorRoute
    }
  }
}

interface CreatorRouteChildren {
  CreatorArchiveRoute: typeof CreatorArchiveRoute
  CreatorMaterialsRoute: typeof CreatorMaterialsRoute
  CreatorRadarRoute: typeof CreatorRadarRoute
  CreatorStudioRoute: typeof CreatorStudioRoute
  CreatorToolsRoute: typeof CreatorToolsRoute
  CreatorIndexRoute: typeof CreatorIndexRoute
}

const CreatorRouteChildren: CreatorRouteChildren = {
  CreatorArchiveRoute: CreatorArchiveRoute,
  CreatorMaterialsRoute: CreatorMaterialsRoute,
  CreatorRadarRoute: CreatorRadarRoute,
  CreatorStudioRoute: CreatorStudioRoute,
  CreatorToolsRoute: CreatorToolsRoute,
  CreatorIndexRoute: CreatorIndexRoute,
}

const CreatorRouteWithChildren =
  CreatorRoute._addFileChildren(CreatorRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BookmarksRoute: BookmarksRoute,
  CreatorRoute: CreatorRouteWithChildren,
  EcommerceRoute: EcommerceRoute,
  EditorRoute: EditorRoute,
  LearnRoute: LearnRoute,
  ObsidianRoute: ObsidianRoute,
  SkillsRoute: SkillsRoute,
  WorkbenchRoute: WorkbenchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
